<?php

/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/OSL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://devdocs.prestashop.com/ for more information.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

namespace PrestaShopBundle\Entity\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Query\Parameter;

/**
 * AttributeGroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Finds attribute groups by language and shop.
     *
     * @param mixed $idLang Language ID
     * @param mixed $idShop Shop ID
     *
     * @return array
     */
    public function findByLangAndShop($idLang, $idShop)
    {
        $attributeGroups = [];

        $qb = $this->createQueryBuilder('ag')
            ->select([
                'ag.id AS attributeGroupId',
                'ag.position AS attributeGroupPosition',
                'ag.isColorGroup AS attributeGroupisColorGroup',
                'agl.name AS attributeGroupName',
                'agl.publicName AS attributeGroupPublicName',
            ])
            ->join('ag.shops', 's')
            ->join('ag.attributeGroupLangs', 'agl')
            ->andWhere('agl.lang = :idLang')
            ->andWhere('s.id = :idShop')
            ->orderBy('attributeGroupPosition')
            ->setParameters(new ArrayCollection([
                new Parameter('idShop', $idShop),
                new Parameter('idLang', $idLang),
            ]));

        $result = $qb->getQuery()->getArrayResult();

        foreach ($result as $attribute) {
            $attributeGroups[$attribute['attributeGroupId']] = $attribute;
        }

        return $attributeGroups;
    }
}
